const brands = [
  { label: 'Apple', value: 'apple' },
  { label: 'Redmi', value: 'redmi' },
  { label: 'Google', value: 'apple' },
  { label: 'OnePlus', value: 'apple' },
  { label: 'Vivo', value: 'apple' },
  { label: 'Oppo', value: 'apple' },
  { label: 'Samsung', value: 'apple' },
  { label: 'Asus', value: 'apple' },
  { label: 'Motorola', value: 'apple' },
];
const categories = [
  { label: 'Mobiles', value: 'mobiles' },
  { label: 'Electronics', value: 'electronics' },
];
const customerRatings = [
  { label: '5 & above', value: '5' },
  { label: '4 & above', value: '4' },
  { label: '3 & above', value: '3' },
  { label: '2 & above', value: '2' },
  { label: '1 & above', value: '1' },
];
const discounts = [
  { label: '10% or more', value: '10' },
  { label: '20% or more', value: '20' },
  { label: '30% or more', value: '30' },
];

const radioInputOptions = [
  { label: 'Mobiles', value: 'mobiles' },
  { label: 'Electronics', value: 'electronics' },
];

const products = [
  {
    productId: 'P-0001',
    productName: 'Redmi Note 7',
    description: '4GB RAM | 64GB storage',
    manufacturer: 'Xiaomi',
    category: 'Mobile',
    company: 'Redmi',
    subCategory: 'Smartphone',
    price: 12000,
    discount: 500,
    offer: 'No offers',
    features: 'Good camera',
    availability: 'yes',
    rating: '5',
  },
  {
    productId: 'P-0002',
    productName: 'iPhone 13 mini',
    description: '8GB RAM | 256GB storage',
    manufacturer: 'Apple',
    category: 'Mobile',
    company: 'Apple',
    subCategory: 'iPhone',
    price: 123000,
    discount: 5000,
    offer: 'Bank offers for ICICI',
    features: 'Best phone',
    availability: 'yes',
    rating: '10',
  },
  {
    productId: 'P-0003',
    productName: 'Pixel 5',
    description: '6GB RAM | 512GB storage',
    manufacturer: 'Google',
    category: 'Mobile',
    company: 'Google',
    subCategory: 'Smartphone',
    price: 93000,
    discount: 7000,
    offer: 'Bank offers for SBI',
    features: 'Great camera',
    availability: 'yes',
    rating: '8',
  },
  {
    productId: 'P-0004',
    productName: 'OnePlus 7',
    description: '8GB RAM | 128GB storage',
    manufacturer: 'OnePlus',
    category: 'Mobile',
    company: 'OnePlus',
    subCategory: 'Smartphone',
    price: 63000,
    discount: 200,
    offer: 'Credit card offer',
    features: 'Great battery life',
    availability: 'yes',
    rating: '7.6',
  },
  {
    productId: 'P-0005',
    productName: 'Samsung M30 ',
    description: '6GB RAM | 128GB storage',
    manufacturer: 'Samsung',
    category: 'Mobile',
    company: 'Samsung',
    subCategory: 'Smartphone',
    price: 33000,
    discount: 2470,
    offer: 'EMI offer',
    features: '',
    availability: 'yes',
    rating: '6.6',
  },
  {
    productId: 'P-0006',
    productName: 'Asus ROG 5 ',
    description: '12GB RAM | 256GB storage',
    manufacturer: 'Asus',
    category: 'Mobile',
    company: 'Asus',
    subCategory: 'Smartphone',
    price: 56789,
    discount: 2408,
    offer: 'Flat 10% off on SBI debit card payment',
    features: '90fps, ultimate gaming phone',
    availability: 'yes',
    rating: '9.6',
  },
  {
    productId: 'P-0007',
    productName: 'Realme X Pro',
    description: '8GB RAM | 256GB storage',
    manufacturer: 'Realme',
    category: 'Mobile',
    company: 'Realme',
    subCategory: 'Smartphone',
    price: 10000,
    discount: 500,
    offer: '5% off on Paytm',
    features: 'Good camera',
    availability: 'yes',
    rating: '5.6',
    createdAt: { $date: { $numberLong: '1656763928601' } },
    updatedAt: { $date: { $numberLong: '1656763928601' } },
  },
  {
    productId: 'P-0008',
    productName: 'Vivo Y30',
    description: '6GB RAM | 128GB storage',
    manufacturer: 'Vivo',
    category: 'Mobile',
    company: 'Vivo',
    subCategory: 'Smartphone',
    price: 19000,
    discount: 500,
    offer: 'Get 10 fair&lovely free',
    features: 'DSLR camera fail',
    availability: 'yes',
    rating: '3.6',
  },
  {
    productId: 'P-0009',
    productName: 'Oppo K10',
    description: '6GB RAM | 64GB storage | 6G',
    manufacturer: 'Oppo',
    category: 'Mobile',
    company: 'Oppo',
    subCategory: 'Smartphone',
    price: 16890,
    discount: 500,
    offer: 'Slice card offer',
    features: 'Latest 6G technology',
    availability: 'yes',
    rating: '1.6',
  },
  {
    productId: 'P-00010',
    productName: 'Moto G60',
    description: '6GB RAM | 64GB storage',
    manufacturer: 'Motorola',
    category: 'Mobile',
    company: 'Motorola',
    subCategory: 'Smartphone',
    price: 18000,
    discount: 1500,
    offer: 'Exchange offer upto 5000',
    features: 'Long lasting battery',
    availability: 'yes',
    rating: '7',
  },
];

export {
  brands,
  categories,
  discounts,
  customerRatings,
  radioInputOptions,
  products,
};
